image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Run
    command: dotnet run --project SimpleCalculatorClient

vscode:
  extensions:
    - muhammad-sammy.csharp
    - https://smartercode.blob.core.windows.net/vscode-extensions/ms-dotnettools.csharp-1.25.4@linux-x64.vsix
    - https://github.com/smarter-code/Uploads/raw/main/formulahendry.dotnet-test-explorer-0.7.8.vsix
